baseURL = "https://www.montferret.dev/"
languageCode = "en-us"
title = "Ferret"
theme = "ferret"

[permalinks]
    pages = "/:title/"

[menu]
  
  [[menu.left]]
    identifier = "repl"
    name = "Try it"
    title = "Try it"
    url = "/try/"
    weight = 1

  [[menu.left]]
    identifier = "docs"
    name = "Docs"
    title = "Project documentation"
    url = "/docs/introduction"
    weight = 2

  [[menu.left]]
    identifier = "blog"
    name = "Blog"
    title = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.right]]
    identifier = "donate"
    name = "Donate"
    title = "Open collective"
    url = "https://opencollective.com/ferret"
    weight = 4

  [[menu.right]]
    identifier = "github"
    name = "GitHub"
    title = "GitHub repository"
    url = "https://github.com/MontFerret/ferret"
    weight = 5