# This is a basic workflow to help you get started with Actions

name: main

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v2
        with:
          stable: true
          go-version: '^1.7'
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.88.1'

      # Runs a single command using the runners shell
      - name: Install Go dependencies
        run: |
          go get
          
      - name: Install theme
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: install

      - name: Build
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: build
          
      - name: Deploy 🚀
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: master # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
          target-folder: .
          clean: true
      - name: Publish
